name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    env:
      USER_DB: test_user
      PASSWORD: test_pass
      HOST: localhost
      PORT: 5432
      DATABASE: test_db
      PGPASSWORD: postgres

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer PostgreSQL
        run: |
          choco install postgresql --params '/Password:postgres' -y
          $env:PATH += ";C:\Program Files\PostgreSQL\16\bin"
          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "Machine")
        shell: powershell

      - name: Attendre le démarrage de PostgreSQL
        run: |
          Start-Sleep -Seconds 10
          $env:PATH += ";C:\Program Files\PostgreSQL\16\bin"
        shell: powershell

      - name: Configurer PostgreSQL
        run: |
          $env:PATH += ";C:\Program Files\PostgreSQL\16\bin"
          $env:PGPASSWORD = "postgres"
          psql -U postgres -c "CREATE USER $env:USER_DB WITH PASSWORD '$env:PASSWORD';"
          psql -U postgres -c "CREATE DATABASE $env:DATABASE OWNER $env:USER_DB;"
        shell: powershell

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter les tests
        run: |
          pytest
